import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/componentsCSS/login.module.css'
import Login from '../components/login'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
      <div className={styles.left}>
        <div className={styles.Logo}>
          <Image src="/Logo blanco.png" alt="Logo" fill />
        </div>
        <div className={styles.paragraph}><b>Now your dream job</b> is the world</div>
          <Login></Login>
      </div>
       
       <div className={styles.right}>
        <Image src="/azulito4.jpg" alt="test" fill></Image>
       </div>
      </main>
    </>
  )
}
