import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/componentsCSS/sidebar.module.css'

export default function Home() {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <main className={styles.main}>
        <div className={styles.left}>

            
            
            
         </div>
        <div className={styles.Logo}>
          <Image src="/logoAzul.png" alt="LogoAzul" fill />
        </div>
        </main>
      </>
    )}     